- id: motoinsight_frontend_lint
  name: Motoinsight Front-End Lint
  entry: motoinsight-lint
  language: node
  args: ['--errors-only', '--fix']
  additional_dependencies: ['@motoinsight/lint@2.0.2']
